### ISSUE TITLE
Sugestão de melhoria na velocidade de carregamento

### ISSUE THREAD

**Issue by Mafarricos** [xsteal/repository.xsteal#1]
Ainda não corri o addon, nem tive tempo para tweakar o código.
Mas pelo que vejo do código parece-me que para cada filmes que apanhas abres logo a página com o link do stream.
Ou seja por cada filme, tens que ir buscar info a outra.
A minha sugestão era para cada filme enviares o link onde se pode obter o stream, e só quando se clica para abrir o filme é que ias buscar o stream resolvido.

Dessa forma a navegação é capaz de ficar mais rápido, pois reduz a quantidade de paginas que tens que fazer scrap só para obteres os filmes.

**Comment by xsteal** [comment]
Done.
